export const techStack = [
    {
        name: "JavaScript",
        icon: require('./icons/javascript.svg').default,
        icon1x: require('./icons/javascript1x.svg').default,
        icon2x: require('./icons/javascript2x.svg').default,
    },
    {
        name: "TypeScript",
        icon: require('./icons/typescript.svg').default,
        icon1x: require('./icons/typescript1x.svg').default,
        icon2x: require('./icons/typescript2x.svg').default,
    },
    {
        name: "React.js",
        icon: require('./icons/react.svg').default,
        icon1x: require('./icons/react1x.svg').default,
        icon2x: require('./icons/react2x.svg').default,
    },
    {
        name: "Next.js",
        icon: require('./icons/nextjs.svg').default,
        icon1x: require('./icons/nextjs1x.svg').default,
        icon2x: require('./icons/nextjs2x.svg').default,
    },
    {
        name: "Node.js",
        icon: require('./icons/node.svg').default,
        icon1x: require('./icons/node1x.svg').default,
        icon2x: require('./icons/node2x.svg').default,
    },
    {
        name: "Express.js",
        icon: require('./icons/express.svg').default,
        icon1x: require('./icons/express1x.svg').default,
        icon2x: require('./icons/express2x.svg').default,
    },
    {
        name: "PostgreSQL",
        icon: require('./icons/postgresql.svg').default,
        icon1x: require('./icons/postgresql1x.svg').default,
        icon2x: require('./icons/postgresql2x.svg').default,
    },
    {
        name: "HTML",
        icon: require('./icons/html.svg').default,
        icon1x: require('./icons/html1x.svg').default,
        icon2x: require('./icons/html2x.svg').default,
    },
    {
        name: "CSS",
        icon: require('./icons/css.svg').default,
        icon1x: require('./icons/css1x.svg').default,
        icon2x: require('./icons/css2x.svg').default,
    },
]

export const otherTools = [
    {
        name: "git",
        icon: require('./icons/git.svg').default,
        icon1x: require('./icons/git1x.svg').default,
        icon2x: require('./icons/git2x.svg').default,
    },
    {
        name: "Github",
        icon: require('./icons/github.svg').default,
        icon1x: require('./icons/github1x.svg').default,
        icon2x: require('./icons/github2x.svg').default,
    },
    {
        name: "npm",
        icon: require('./icons/npm.svg').default,
        icon1x: require('./icons/npm1x.svg').default,
        icon2x: require('./icons/npm2x.svg').default,
    },
    {
        name: "Webpack",
        icon: require('./icons/webpack.svg').default,
        icon1x: require('./icons/webpack1x.svg').default,
        icon2x: require('./icons/webpack2x.svg').default,
    },
    {
        name: "GraphQL",
        icon: require('./icons/graphql.svg').default,
        icon1x: require('./icons/graphql1x.svg').default,
        icon2x: require('./icons/graphql2x.svg').default,
    },
    {
        name: "JSON",
        icon: require('./icons/json.svg').default,
        icon1x: require('./icons/json1x.svg').default,
        icon2x: require('./icons/json2x.svg').default,
    },
    {
        name: "AJAX",
        icon: require('./icons/ajax.svg').default,
        icon1x: require('./icons/ajax1x.svg').default,
        icon2x: require('./icons/ajax2x.svg').default,
    },
    {
        name: "jQuery",
        icon: require('./icons/jquery.svg').default,
        icon1x: require('./icons/jquery1x.svg').default,
        icon2x: require('./icons/jquery2x.svg').default,
    },
    {
        name: "Apache",
        icon: require('./icons/apache.png'),
        icon1x: require('./icons/apache1x.png'),
        icon2x: require('./icons/apache2x.png'),
    },
    {
        name: "Tailwind",
        icon: require('./icons/tailwind.svg').default,
        icon1x: require('./icons/tailwind1x.svg').default,
        icon2x: require('./icons/tailwind2x.svg').default,
    },
    {
        name: "Bootstrap",
        icon: require('./icons/bootstrap.svg').default,
        icon1x: require('./icons/bootstrap1x.svg').default,
        icon2x: require('./icons/bootstrap2x.svg').default,
    },
    {
        name: "Figma",
        icon: require('./icons/figma.svg').default,
        icon1x: require('./icons/figma1x.svg').default,
        icon2x: require('./icons/figma2x.svg').default,
    },
    {
        name: "Bulma.io",
        icon: require('./icons/bulma.svg').default,
        icon1x: require('./icons/bulma1x.svg').default,
        icon2x: require('./icons/bulma2x.svg').default,
    },
    {
        name: "Strapi",
        icon: require('./icons/strapi.svg').default,
        icon1x: require('./icons/strapi1x.svg').default,
        icon2x: require('./icons/strapi2x.svg').default,
    },
    {
        name: "dbDesigner",
        icon: require('./icons/dbdesigner.png'),
        icon1x: require('./icons/dbdesigner1x.png'),
        icon2x: require('./icons/dbdesigner2x.png'),
    },
    {
        name: "JWT Token",
        icon: require('./icons/jwt.svg').default,
        icon1x: require('./icons/jwt1x.svg').default,
        icon2x: require('./icons/jwt2x.svg').default,
    },
    {
        name: "HTTPie",
        icon: require('./icons/httpie.svg').default,
        icon1x: require('./icons/httpie1x.svg').default,
        icon2x: require('./icons/httpie2x.svg').default,
    },
]